name = "cmo"
uuid = "8fef1f49-b762-4057-bd17-4872457395b4"
version = "0.1.0"
authors = ["Ashrith Sagar <ashrithy@iisc.ac.in>"]

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ForwardDiff = "1.2.2"
JuliaFormatter = "2.1.6"
LinearAlgebra = "1.12.0"
ReverseDiff = "1.16.1"
Test = "1.11.0"
Zygote = "0.7.10"
