[project]
name = "CMO2025A0"
version = "0.1.0"
description = "E0230-CMO-2025 Assignment-0"
authors = [{ name = "Ashrith Sagar", email = "ashrithy@iisc.ac.in" }]
readme = "../README.md"
requires-python = ">=3.10"
